apps/turk/config/routes.rb
Turk::Application.routes.draw do
  resources :works do
    member do
      put :complete
    end
  end

  resources :mechanical_turks

end

apps/turk/app/models/mechanical_turk.rb
class MechanicalTurk < ActiveRecord::Base
  attr_accessible :name
end

apps/turk/app/models/task_service.rb
class TaskService
  def self.notify_completion(task_id)
    url =  "http://localhost:3001/tasks/#{task_id}/complete"
    RestClient.put url, {}.to_json
  end
end

apps/turk/app/models/work.rb
class Work < ActiveRecord::Base
  attr_accessible :description, :mechanical_turk_id, :status, :task_id
  belongs_to :mechanical_turk
  after_create :assign_turk

  def complete!
    self.update_attributes!(status: 'completed')
    TaskService.notify_completion(task_id)
  end

  private

  def assign_turk
    self.status = 'created'
    self.mechanical_turk = MechanicalTurk.first(offset: rand(MechanicalTurk.count))
    self.save!
  end
end

apps/turk/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

apps/turk/app/controllers/mechanical_turks_controller.rb
class MechanicalTurksController < ApplicationController
  # GET /mechanical_turks
  # GET /mechanical_turks.json
  def index
    @mechanical_turks = MechanicalTurk.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mechanical_turks }
    end
  end

  # GET /mechanical_turks/1
  # GET /mechanical_turks/1.json
  def show
    @mechanical_turk = MechanicalTurk.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mechanical_turk }
    end
  end

  # GET /mechanical_turks/new
  # GET /mechanical_turks/new.json
  def new
    @mechanical_turk = MechanicalTurk.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mechanical_turk }
    end
  end

  # GET /mechanical_turks/1/edit
  def edit
    @mechanical_turk = MechanicalTurk.find(params[:id])
  end

  # POST /mechanical_turks
  # POST /mechanical_turks.json
  def create
    @mechanical_turk = MechanicalTurk.new(params[:mechanical_turk])

    respond_to do |format|
      if @mechanical_turk.save
        format.html { redirect_to @mechanical_turk, notice: 'Mechanical turk was successfully created.' }
        format.json { render json: @mechanical_turk, status: :created, location: @mechanical_turk }
      else
        format.html { render action: "new" }
        format.json { render json: @mechanical_turk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mechanical_turks/1
  # PUT /mechanical_turks/1.json
  def update
    @mechanical_turk = MechanicalTurk.find(params[:id])

    respond_to do |format|
      if @mechanical_turk.update_attributes(params[:mechanical_turk])
        format.html { redirect_to @mechanical_turk, notice: 'Mechanical turk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mechanical_turk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mechanical_turks/1
  # DELETE /mechanical_turks/1.json
  def destroy
    @mechanical_turk = MechanicalTurk.find(params[:id])
    @mechanical_turk.destroy

    respond_to do |format|
      format.html { redirect_to mechanical_turks_url }
      format.json { head :no_content }
    end
  end
end

apps/turk/app/controllers/works_controller.rb
class WorksController < ApplicationController
  # GET /works
  # GET /works.json
  def index
    @works = Work.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @works }
    end
  end

  # GET /works/1
  # GET /works/1.json
  def show
    @work = Work.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/new
  # GET /works/new.json
  def new
    @work = Work.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work }
    end
  end

  # GET /works/1/edit
  def edit
    @work = Work.find(params[:id])
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render json: @work, status: :created, location: @work }
      else
        format.html { render action: "new" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /works/1
  # PUT /works/1.json
  def update
    @work = Work.find(params[:id])

    respond_to do |format|
      if @work.update_attributes(params[:work])
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work = Work.find(params[:id])
    @work.destroy

    respond_to do |format|
      format.html { redirect_to works_url }
      format.json { head :no_content }
    end
  end

  def complete
    work = Work.find_by_id!(params[:id])
    work.complete!
    redirect_to work
  end
end

apps/turk/app/helpers/application_helper.rb
module ApplicationHelper
end

apps/turk/app/helpers/mechanical_turks_helper.rb
module MechanicalTurksHelper
end

apps/turk/app/helpers/works_helper.rb
module WorksHelper
end

apps/turk/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Turk</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

apps/turk/app/views/mechanical_turks/_form.html.erb
<%= form_for(@mechanical_turk) do |f| %>
  <% if @mechanical_turk.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mechanical_turk.errors.count, "error") %> prohibited this mechanical_turk from being saved:</h2>

      <ul>
      <% @mechanical_turk.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

apps/turk/app/views/mechanical_turks/edit.html.erb
<h1>Editing mechanical_turk</h1>

<%= render 'form' %>

<%= link_to 'Show', @mechanical_turk %> |
<%= link_to 'Back', mechanical_turks_path %>

apps/turk/app/views/mechanical_turks/index.html.erb
<h1>Listing mechanical_turks</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mechanical_turks.each do |mechanical_turk| %>
  <tr>
    <td><%= mechanical_turk.id %></td>
    <td><%= mechanical_turk.name %></td>
    <td><%= link_to 'Show', mechanical_turk %></td>
    <td><%= link_to 'Edit', edit_mechanical_turk_path(mechanical_turk) %></td>
    <td><%= link_to 'Destroy', mechanical_turk, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Mechanical turk', new_mechanical_turk_path %>

apps/turk/app/views/mechanical_turks/new.html.erb
<h1>New mechanical_turk</h1>

<%= render 'form' %>

<%= link_to 'Back', mechanical_turks_path %>

apps/turk/app/views/mechanical_turks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @mechanical_turk.name %>(<%=@mechanical_turk.id%>)
</p>


<%= link_to 'Edit', edit_mechanical_turk_path(@mechanical_turk) %> |
<%= link_to 'Back', mechanical_turks_path %>

apps/turk/app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br />
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :mechanical_turk_id %><br />
    <%= f.number_field :mechanical_turk_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

apps/turk/app/views/works/edit.html.erb
<h1>Editing work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

apps/turk/app/views/works/index.html.erb
<h1>Listing works</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Task</th>
    <th>Mechanical turk</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @works.each do |work| %>
  <tr>
    <td><%= work.description %></td>
    <td><%= work.task_id %></td>
    <td><%= work.mechanical_turk.name if work.mechanical_turk %></td>
    <td><%= work.status %></td>
    <td><%= link_to 'Show', work %></td>
    <td><%= link_to 'Edit', edit_work_path(work) %></td>
    <td><%= link_to 'Destroy', work, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Work', new_work_path %>

apps/turk/app/views/works/new.html.erb
<h1>New work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

apps/turk/app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @work.description %>
</p>

<p>
  <b>Task:</b>
  <%= @work.task_id %>
</p>

<p>
  <b>Mechanical turk:</b>
  <%= @work.mechanical_turk_id %>
</p>

<p>
  <b>Status:</b>
  <%= @work.status %>
</p>

<%= form_for(@work, url: complete_work_path(@work)) do |f| %>
  <div class="actions">
    <%= f.submit 'Complete' %>
  </div>
<% end %>
<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>